version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app-php
    image: mauricioumelo/php
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - app-php
    restart: always

  nginx:
    image: nginx:latest
    container_name: app-nginx
    ports:
      - 9088:80
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-php
    restart: always

networks:
  app-php:
    driver: bridge
